import { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { MapPin, Plus, Trash2 } from 'lucide-react';
import { zonesApi } from '../lib/api';
import type { Zone } from '../lib/api';

export function ZonesPage() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [zones, setZones] = useState<Zone[]>([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [formData, setFormData] = useState({
    name: '',
    type: 'warehouse',
    description: '',
    capacity: '',
    parent_zone_id: searchParams.get('parent') || '',
  });

  useEffect(() => {
    loadZones();
  }, []);

  const loadZones = async () => {
    try {
      const { data } = await zonesApi.getAll();
      setZones(data);
    } catch (error) {
      console.error('Failed to load zones:', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    // Open form if parent_zone_id is in URL
    if (searchParams.get('parent')) {
      setShowForm(true);
    }
  }, [searchParams]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const payload: any = {
        name: formData.name,
        type: formData.type,
        description: formData.description || undefined,
        capacity: formData.capacity ? parseInt(formData.capacity) : undefined,
        parent_zone_id: formData.parent_zone_id ? parseInt(formData.parent_zone_id) : undefined,
        is_active: true,
      };
      // code will be auto-generated by backend
      await zonesApi.create(payload);
      setShowForm(false);
      setFormData({ name: '', type: 'warehouse', description: '', capacity: '', parent_zone_id: '' });
      loadZones();
      navigate('/zones'); // Remove query params
    } catch (error) {
      console.error('Failed to create zone:', error);
    }
  };

  const handleZoneClick = (zoneId: number) => {
    navigate(`/zones/${zoneId}`);
  };

  const handleDeleteZone = async (e: React.MouseEvent, zone: Zone) => {
    e.stopPropagation(); // Prevent navigation when clicking delete

    if (!confirm(`Zone "${zone.name}" (${zone.code}) wirklich löschen?`)) {
      return;
    }

    try {
      await zonesApi.delete(zone.zone_id);
      loadZones();
    } catch (error) {
      console.error('Failed to delete zone:', error);
      alert('Fehler beim Löschen der Zone. Prüfe ob die Zone Unterzonen oder Geräte enthält.');
    }
  };

  const zoneTypes = [
    { value: 'warehouse', label: 'Lager', icon: '🏭' },
    { value: 'rack', label: 'Regal', icon: '🗄️' },
    { value: 'gitterbox', label: 'Gitterbox', icon: '📦' },
  ];

  // Get parent zone name if creating subzone
  const parentZone = formData.parent_zone_id
    ? zones.find((z) => z.zone_id === parseInt(formData.parent_zone_id))
    : null;

  // Filter root zones (no parent) for main view
  const rootZones = zones.filter((z) => !z.parent_zone_id);

  if (loading) {
    return (
      <div className="flex items-center justify-center h-96">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-accent-red"></div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold text-white mb-2">Zonen</h2>
          <p className="text-gray-400">{rootZones.length} Hauptzonen • {zones.length} gesamt</p>
        </div>
        <button
          onClick={() => setShowForm(!showForm)}
          className="flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-accent-red to-red-700 text-white font-semibold rounded-xl hover:shadow-lg hover:shadow-accent-red/50 transition-all transform hover:scale-105"
        >
          <Plus className="w-5 h-5" />
          {parentZone ? 'Unterzone erstellen' : 'Zone erstellen'}
        </button>
      </div>

      {/* Create Form */}
      {showForm && (
        <div className="glass-dark rounded-2xl p-6 border-2 border-accent-red/30">
          <h3 className="text-xl font-bold text-white mb-4">
            {parentZone ? `Unterzone in ${parentZone.name} erstellen` : 'Neue Zone erstellen'}
          </h3>
          {parentZone && (
            <div className="mb-4 p-3 bg-white/5 rounded-lg">
              <p className="text-sm text-gray-400">
                Übergeordnete Zone: <span className="text-white font-semibold">{parentZone.name}</span> ({parentZone.code})
              </p>
            </div>
          )}
          <form onSubmit={handleSubmit} className="space-y-4">
            <input
              type="text"
              value={formData.name}
              onChange={(e) => setFormData({ ...formData, name: e.target.value })}
              placeholder="Name (z.B. Lager Weidelbach, Regal A1, Fach 03)"
              required
              className="w-full px-4 py-3 bg-white/10 backdrop-blur-md border border-white/20 rounded-xl text-white placeholder-gray-500 focus:outline-none focus:border-accent-red transition-colors"
            />
            <select
              value={formData.type}
              onChange={(e) => setFormData({ ...formData, type: e.target.value })}
              className="w-full px-4 py-3 bg-white/10 backdrop-blur-md border border-white/20 rounded-xl text-white focus:outline-none focus:border-accent-red transition-colors"
            >
              {zoneTypes.map((type) => (
                <option key={type.value} value={type.value} className="bg-dark-200">
                  {type.icon} {type.label}
                </option>
              ))}
            </select>
            <input
              type="number"
              value={formData.capacity}
              onChange={(e) => setFormData({ ...formData, capacity: e.target.value })}
              placeholder="Kapazität (optional)"
              className="w-full px-4 py-3 bg-white/10 backdrop-blur-md border border-white/20 rounded-xl text-white placeholder-gray-500 focus:outline-none focus:border-accent-red transition-colors"
            />
            <textarea
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              placeholder="Beschreibung (optional)"
              rows={3}
              className="w-full px-4 py-3 bg-white/10 backdrop-blur-md border border-white/20 rounded-xl text-white placeholder-gray-500 focus:outline-none focus:border-accent-red transition-colors resize-none"
            />
            <div className="flex gap-3">
              <button
                type="submit"
                className="flex-1 py-3 bg-accent-red text-white font-semibold rounded-xl hover:bg-red-700 transition-colors"
              >
                Erstellen
              </button>
              <button
                type="button"
                onClick={() => setShowForm(false)}
                className="px-6 py-3 glass text-gray-400 hover:text-white font-semibold rounded-xl transition-colors"
              >
                Abbrechen
              </button>
            </div>
          </form>
        </div>
      )}

      {/* Zones Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {rootZones.map((zone) => {
          const typeInfo = zoneTypes.find((t) => t.value === zone.type);
          return (
            <div
              key={zone.zone_id}
              className="glass rounded-xl p-5 hover:bg-white/20 transition-all cursor-pointer group relative"
              onClick={() => handleZoneClick(zone.zone_id)}
            >
              <button
                onClick={(e) => handleDeleteZone(e, zone)}
                className="absolute top-3 right-3 p-2 glass-dark rounded-lg text-red-400 hover:text-red-300 hover:bg-red-900/20 opacity-0 group-hover:opacity-100 transition-all z-10"
                title="Zone löschen"
              >
                <Trash2 className="w-4 h-4" />
              </button>
              <div className="flex items-start gap-4">
                <div className="text-3xl">{typeInfo?.icon || '📦'}</div>
                <div className="flex-1 min-w-0">
                  <h3 className="font-bold text-white truncate mb-1 group-hover:text-accent-red transition-colors">
                    {zone.name}
                  </h3>
                  <p className="text-sm text-gray-400 mb-2 font-mono">{zone.code}</p>
                  <div className="flex items-center gap-3 text-xs">
                    <span className="text-gray-500">{typeInfo?.label}</span>
                    {zone.capacity && (
                      <span className="text-gray-500">Kapazität: {zone.capacity}</span>
                    )}
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {rootZones.length === 0 && !showForm && (
        <div className="text-center py-12">
          <MapPin className="w-16 h-16 text-gray-600 mx-auto mb-4" />
          <p className="text-gray-400 mb-4">Noch keine Zonen vorhanden</p>
          <button
            onClick={() => setShowForm(true)}
            className="text-accent-red hover:text-red-500 font-semibold"
          >
            Erste Zone erstellen
          </button>
        </div>
      )}
    </div>
  );
}
